return {
    image = "data/textures/MCM_Cosmic_Overhaul.png",
    pages = {
        {
            title = "Captain Travel",
            options = {
                {
                    key = "captainEfficientTravelMultiplier",
                    type = "number",
                    title = "Travel Duration Multiplier",
                    description = "Scales captain travel command duration. Lower is faster.",
                    default = 0.90,
                    min = 0.10,
                    max = 2.00,
                },
                {
                    key = "captainSafeAttackChanceMultiplier",
                    type = "number",
                    title = "Attack Chance Multiplier",
                    description = "Scales ambush/attack chance during captain travel. Lower is safer.",
                    default = 0.85,
                    min = 0.00,
                    max = 2.00,
                },
                {
                    key = "enableGateTravelPriority",
                    type = "bool",
                    title = "Enable Gate Travel Priority",
                    description = "Prefers gate-assisted routing when possible for captain travel logic.",
                    default = true,
                },
            },
        },
        {
            title = "Long Range Area",
            options = {
                {
                    key = "extraLongRangeTradeBonus",
                    type = "number",
                    title = "Trade/Procure Extra Area Bonus",
                    description = "Flat bonus added to Trade and Procure command area size.",
                    default = 0,
                    min = 0,
                    max = 30,
                },
                {
                    key = "extraLongRangeSellBonus",
                    type = "number",
                    title = "Sell Extra Area Bonus",
                    description = "Flat bonus added to Sell command area size.",
                    default = 0,
                    min = 0,
                    max = 30,
                },
                {
                    key = "extraLongRangeMineBonus",
                    type = "number",
                    title = "Mine Extra Area Bonus",
                    description = "Flat bonus added to Mine command area size.",
                    default = 0,
                    min = 0,
                    max = 30,
                },
                {
                    key = "extraLongRangeRefineBonus",
                    type = "number",
                    title = "Refine Extra Area Bonus",
                    description = "Flat bonus added to Refine command area size.",
                    default = 0,
                    min = 0,
                    max = 30,
                },
                {
                    key = "extraLongRangeSalvageBonus",
                    type = "number",
                    title = "Salvage Extra Area Bonus",
                    description = "Flat bonus added to Salvage command area size.",
                    default = 0,
                    min = 0,
                    max = 30,
                },
                {
                    key = "extraLongRangeScoutBonus",
                    type = "number",
                    title = "Scout Extra Area Bonus",
                    description = "Flat bonus reserved for Scout area scaling integrations.",
                    default = 0,
                    min = 0,
                    max = 30,
                },
            },
        },
        {
            title = "Systems",
            options = {
                {
                    key = "enableProfitableStations",
                    type = "bool",
                    title = "Enable Profitable Stations",
                    description = "Enables periodic station income simulation enhancements.",
                    default = true,
                },
                {
                    key = "profitableStationsInterval",
                    type = "number",
                    title = "Profitable Stations Interval (s)",
                    description = "Update interval for profitable stations simulation.",
                    default = 600,
                    min = 30,
                    max = 7200,
                },
                {
                    key = "profitableStationsPayoutMultiplier",
                    type = "number",
                    title = "Profitable Stations Payout Multiplier",
                    description = "Scales profitable stations payout values.",
                    default = 1.00,
                    min = 0.10,
                    max = 10.00,
                },
                {
                    key = "profitableStationsSpawnTraderWhenLoaded",
                    type = "bool",
                    title = "Spawn Trader In Loaded Sectors",
                    description = "Allows trader presence logic while sector is loaded.",
                    default = true,
                },
                {
                    key = "enableExoticLegendarySalvage",
                    type = "bool",
                    title = "Enable Exotic/Legendary Salvage",
                    description = "Applies weighted rarity upgrades to salvage-generated items.",
                    default = true,
                },
            },
        },
        {
            title = "Diagnostics",
            options = {
                {
                    key = "debugLogs",
                    type = "bool",
                    title = "Enable Cosmic Overhaul Debug Logs",
                    description = "Enables informational debug prints in logs for CO systems.",
                    default = false,
                },
            },
        },
    },
}
